#!/bin/bash

LIB=`dirname $0`/lib/commons-io-2.4.jar
SRC=`dirname $0`/bin/
DOC=`dirname $0`/doc/

if [ "$OSTYPE" == "linux-gnu" ]; then
  CP="$SRC:$DOC:$LIB"
elif [ "$OSTYPE" == "darwin"* ]; then
  CP="$SRC:$DOC:$LIB"
else
  CP="$SRC;$DOC;$LIB"
fi

java -cp $CP com.digitalgeyser.jigger.Main $@

