#!/bin/bash

# Remove and create bin directory.
rm -rf bin/
mkdir bin

# First we build a microjig out of the java source files, so that we can then execute a main jig build.
find src/ -name '*.java' | xargs javac 
