#!/bin/bash

CP=lib/commons-io-2.4.jar
# Remove and create bin directory.
rm -rf bin/
mkdir bin

cp -R src/* bin/

find bin/ -name '*.java' | xargs javac -cp $CP

find bin/ -name '*.java' -exec rm -rf {} \;
